[package]
name = 'tokenizeRs'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = "0.6"
polars = { version = "0.35.4", features = ["lazy"]}
rayon = "1.8.0"
serde_json = "1.0.108"
