# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tokenizeRs_wrappers", use_symbols = TRUE, package_name = "tokenizeRs")

#' @docType package
#' @usage NULL
#' @useDynLib tokenizeRs, .registration = TRUE
NULL

#' @export
decode_tokens <- function(tensor) .Call(wrap__decode_tokens, tensor)

#' @export
decode_batch <- function(batch) .Call(wrap__decode_batch, batch)


# nolint end
