# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tokenizeRs_wrappers", use_symbols = TRUE, package_name = "tokenizeRs")

#' @docType package
#' @usage NULL
#' @useDynLib tokenizeRs, .registration = TRUE
NULL

#' add two integers supplied to rust
#' @export
add_nums <- function(x, y) .Call(wrap__add_nums, x, y)


# nolint end
